name: todo_sql_lite
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  built_value: ^8.3.3
  freezed_annotation: ^2.2.0
  freezed: ^2.2.1
  json_annotation: ^4.5.0
  get_it: ^7.2.0
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.7
  flutter_bloc: ^8.1.1
  retrofit: ^3.0.0
  equatable: 2.0.3
  dio: ^4.0.6
  uuid: ^3.0.6
  path: ^1.8.2
  path_provider: ^2.0.11
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.1.11
  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0
  built_value_generator: ^8.3.3


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
